# Generated by Django 4.0.2 on 2022-02-16 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_visit',
            name='check_in',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 0, 42, 1, 951220)),
        ),
        migrations.AlterField(
            model_name='customer_visit',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
