# Generated by Django 4.0.2 on 2022-02-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_customer_visit_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_visit',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer_visit',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
