# Generated by Django 3.1.7 on 2022-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20220217_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
